[workspace]
resolver = "3"
members = [
    "crates/prism-math",
    "crates/prism-core",
    "crates/prism-props",
    "crates/prism-text",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["Alva"]

[workspace.dependencies]
prism-math = { path = "crates/prism-math" }
prism-core = { path = "crates/prism-core" }
prism-props = { path = "crates/prism-props" }
prism-text = { path = "crates/prism-text" }

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "warn"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
debug = 1
lto = "thin"
codegen-units = 4
